--------------------------------------------------------
--  DDL for Table TB_CLIENTE
--------------------------------------------------------

  CREATE TABLE "TESTEJTS"."TB_CLIENTE"
   (	"ID_CLIENTE" NUMBER(*,0),
	"NOME" VARCHAR2(500 BYTE),
	"LOCAL_NASCIMENTO" VARCHAR2(500 BYTE),
	"VERSAO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TESTEJTS_TS" ;
REM INSERTING into TESTEJTS.TB_CLIENTE
SET DEFINE OFF;
Insert into TESTEJTS.TB_CLIENTE (ID_CLIENTE,NOME,LOCAL_NASCIMENTO,VERSAO) values (1,'SILVIO HOHNE','Rio Claro',2241);
Insert into TESTEJTS.TB_CLIENTE (ID_CLIENTE,NOME,LOCAL_NASCIMENTO,VERSAO) values (2,'RENATO HOHNE','Sao Paulo',2352);
Insert into TESTEJTS.TB_CLIENTE (ID_CLIENTE,NOME,LOCAL_NASCIMENTO,VERSAO) values (3,'ANA CLAUDIA','Rio de Janeiro',2413);
--------------------------------------------------------
--  DDL for Index SYS_C007303
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTEJTS"."SYS_C007303" ON "TESTEJTS"."TB_CLIENTE" ("ID_CLIENTE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TESTEJTS_TS" ;
--------------------------------------------------------
--  Constraints for Table TB_CLIENTE
--------------------------------------------------------

  ALTER TABLE "TESTEJTS"."TB_CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "TESTEJTS"."TB_CLIENTE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "TESTEJTS"."TB_CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TESTEJTS_TS"  ENABLE;
